name: Build first before deploy to Vercel

on:
  push:
    branches: [master]
jobs:
  build-angular-and-scully-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - run: npm run scully
      - run: npm run scully:serve
      - name: Custom Build and deploy
        shell: bash
        run: |
          sleep 10 &&
          node CustomBuildReducer.mjs
          npm install --global vercel@latest
          vercel deploy dist/static-coveraged --prod --token=${{ secrets.VERCEL_TOKEN }}
