name: Build first before deploy to Cloudflare Pages

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"
jobs:
  build-angular-and-scully-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - run: npm run scully
      - name: Run both scully serve and custom build
        run: |
          npm run scully:serve &
          sleep 5 && node customBuildReducer.mjs
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          directory: ./dist/static-coveraged
