name: Build first before deploy to Vercel

on:
  push:
    branches: [master]
jobs:
  build-angular-and-scully-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - run: npm run scully
      - run: npm install --global vercel@latest
      - run: vercel deploy dist/static --prod --token=${{ secrets.VERCEL_TOKEN }}
